<?php

/**
 * @file
 * Combine the rePortal system with SIDE project
 */

/**
 * Implemetation of hook_menu()
 */
function bindrePortal_menu(){
    //rewrite my projects page for researcher
    $menus['researcher/projects'] = array(
        'title' => t('My research projects'),
        'description' => t('List projects for researcher'),
        'page callback' => 'researcher_projects_callback',
        'access callback' => 'user_is_logged_in',
        'type' => MENU_CALLBACK,
    );
    //rewrite my projects page for participant
    $menus['person/projects'] = array(
        'title' => t('My participating projects'),
        'description' => t('List all projects the user has participated.'),
        'page callback' => 'person_projects_callback',
        'access callback' => 'user_is_logged_in',
        'type' => MENU_CALLBACK,
    );
    return $menus;
}

/**
 * Implementation of hook_create_project().
 */
function bindrePortal_create_project($project){
    //insert into research_project table
    $check = 'SELECT COUNT(*) FROM {research_project} WHERE idproject=%d';
    if(!db_result(db_query($check, $project->id))){
        $insert = 'INSERT INTO {research_project} (idproject, name, description) VALUES(%d, "%s", "%s")';
        db_query($insert, $project->id, $project->name, $project->introduction);
    }
    
    
    //bind physical activity tool
    $tool_id = variable_get('physical_activity_tool', null);
    if($tool_id){
        $insert = 'INSERT INTO {research_project_tools_list} (project, tool, created) VALUES(%d, %d, NOW())';
        db_query($insert, $project->id, $tool_id);
        
        //add default link
        $l_title1 = 'View my data';
        $l_url1 = url('person_chart');
        $l_weight1 = 1;
        $l_permission1 = 'PUBLIC';
        
        $add = 'INSERT INTO {research_project_tool_links}(project, tool, title, url, weight, permission, created, changed) VALUES(%d, %d, "%s", "%s", %d, "%s", NOW(), NOW())';
        db_query($add, $project->id, $tool_id, $l_title1, $l_url1, $l_weight1, $l_permission1);
    
        //add default link
        $l_title2 = 'View all data';
        $l_url2 = url('chart');
        $l_weight2 = 2;
        $l_permission2 = 'CONFIDENTIAL';
        db_query($add, $project->id, $tool_id, $l_title2, $l_url2, $l_weight2, $l_permission2);
    }
    
}

/**
 * Implementation of hook_project_join_new_participant().
 */
function bindrePortal_project_join_new_participant($project, $uid){
    //check if user in the project or not
    $check = 'SELECT project_code FROM {project_code} WHERE idperson=%d AND idproject=%d';
    $code = db_result(db_query($check, $uid, $project));
    if(!$code){
        $insert = 'INSERT INTO {project_code} (idperson, idproject) VALUES(%d , %d)';
        db_query($insert, $uid, $project);
        $id = mysql_insert_id();
        
        //generate project code;
        $code = $id + 100000;
        $update = 'UPDATE {project_code} SET project_code ="%s" WHERE idprojectcode=%d';
        db_query($update, ''.$code, $id);
    }
}

/**
 * Implementation of hook_project_participant_card_info($pid, $uid)
 */
function bindrePortal_project_participant_card_info($pid, $uid){
    
    if($uid>0){
        //get project code
        $get = 'SELECT project_code FROM {project_code} WHERE idperson=%d AND idproject=%d';
        $code = db_result(db_query($get, $uid, $pid));
        
        if($code){
            $card['project_code'] = array(
                'name' => t('Project code'),
                'value'=> $code,
                'weight' => 0,
            );
        }
    }
    return $card;
}

/**
 * Menu callback for researcher/projects/
 */
function researcher_projects_callback(){
    global $user;
    if($user->uid){
        $header = array(
            array('data'=>'Project name'),
            array('data'=>'Roles'),
            array('data'=>'Join at'),
            
        );
        $rows = array();
        
        $sql = 'SELECT project, changed FROM {research_projects_persons_list} WHERE user='.$user->uid.' AND role IN ("researcher", "creator") AND active=1 ';
        $res = pager_query($sql, 10);
        while($r = db_fetch_object($res)){
            $project = load_project($r->project, 'id');
            $roles = is_project_participant($project->id, $user->uid);
            $roles_data = '';
            foreach($roles as $role){
                $roles_data.= ' '.$role;
            }
            
            if($project){
                $rows[] = array(
                    l($project->name, generate_project_url($project->path)),
                    $roles_data,
                    $r->changed,
                );
            }
        }
        $content.= theme_table($header, $rows);
        $content.= theme_pager();
        return $content;
        
    }
    
}

/**
 * Menu callback for person/projects
 */
function person_projects_callback(){
    global $user;
    if($user->uid){
        $header = array(
            array('data'=>'Project name'),
            array('data'=>'Rroject code'),
            array('data'=>'Join at'),
            
        );
        $rows = array();
        
        $sql = 'SELECT project, changed FROM {research_projects_persons_list} WHERE user='.$user->uid.' AND role="participant" AND active=1 ';
        $res = pager_query($sql, 10);
        while($r = db_fetch_object($res)){
            $project = load_project($r->project, 'id');
            $code = get_project_code($project->id, $user->uid);
            foreach($roles as $role){
                $roles_data.= ' '.$role;
            }
            
            if($project){
                $rows[] = array(
                    l($project->name, generate_project_url($project->path)),
                    $code,
                    $r->changed,
                );
            }
        }
        $content.= theme_table($header, $rows);
        $content.= theme_pager();
        return $content;
        
    }
}