<?php
// $Id$

/**
* @file
* Module for fetching data from Goodreads.com.
* This module provides block content retrieved from a
* Goodreads.com bookshelf.
* @see http://www.goodreads.com
*/
/**
* Implementation of hook_menu()
*/
function chart_menu() {
  $items['chart'] = array(
    'title' => t('Observation'),
    'page callback' => 'show_template',
    'access callback' => user_is_logged_in,
    'type' => MENU_CALLBACK,
  );
  $items['person_chart'] = array(
    'title' => t('Observation'),
    'page callback' => 'show_person_template',
    'access callback' => user_is_logged_in,
    'type' => MENU_CALLBACK,
  );
  $items['chart/handle_data'] = array(
    'title' => t('Handle json data'),
    'page callback' => 'json_chart_handle_data_callback',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implementation of hook_theme()
 */
function chart_theme() {
    return array(
	'show_chart' => array(
       'template' => 'chart_display',
       ),
	  'show_person_chart'=>array(
		'template'=>'chart_person_display',
		),
    );
}
 
/**
 * Menu callback for researcher chart
 */ 
 
function show_template() {
		global $user;
		//drupal_set_html_head('<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js" type="text/javascript" /></script>');
		//drupal_add_js($module_path.'/calendar/jquery-1.3.1.js');
		$module_path = drupal_get_path('module', 'chart');
		drupal_add_js($module_path.'/calendar/ui/ui.core.js');
		drupal_add_js($module_path.'/calendar/ui/ui.datepicker.js');
		drupal_add_js($module_path.'/js/highcharts.js');
		drupal_add_js($module_path.'/js/modules/exporting.js');
		drupal_add_js($module_path.'/js/themes/grid.js');
		drupal_add_js($module_path.'/highslide/highslide.config.js');
		drupal_add_js($module_path.'/highslide/highslide-full.min.js');
		drupal_add_js($module_path.'/js/calendar.js');
		drupal_add_js($module_path.'/js/chart_display.js');

		drupal_add_css($module_path.'/calendar/demos/shadow.css');
		drupal_add_css($module_path.'/highslide/highslide.css');
		drupal_add_css($module_path.'/calendar/themes/base/ui.all.css');
		drupal_add_css($module_path.'/calendar/demos/demos.css');
		
		//add settings to js
		//Drupal.settings.chart.module_path
		drupal_add_js(array('chart'=>array('module_path'=>$module_path)),'setting');
		//Drupal.settings.chart.current_user
		drupal_add_js(array('chart'=>array('current_user'=>$user->uid)),'setting');
		//Drupal.settings.chart.handle_data
		drupal_add_js(array('chart'=>array('handle_data'=>url('chart/handle_data'))),'setting');
		//Drupal.settings.chart.getprojects
		drupal_add_js(array('chart'=>array('getprojects'=>url('researcher/projects/json'))),'setting');
		//Drupal.settings.chart.getprojectpersons
		drupal_add_js(array('chart'=>array('getprojectpersons'=>url('researcher/projects/persons/json/'))),'setting');
		//Drupal.settings.chart.getpersonobservation
		drupal_add_js(array('chart'=>array('getpersonobservation'=>url('person/observations/get/json'))),'setting');
		
		$content = theme('show_chart');
		$content.= '<h3>Recent uploading</h3>';
		$header = array(
		      array('data'=>'Upload time'),
		      array('data'=>'Project'),
		      array('data'=>'Status'),
		);
		
		//get researcher's project
		$get_projects = "SELECT nid FROM {node} AS n WHERE type='%s' AND n.uid=%d";
		$type = 'researchproject';
		$res = db_query($get_projects,$type,$user->uid);
		if($pid = db_result($res)){
		  $where_part = "( f.idproject=$pid ";
		  while($pid = db_result($res)){
		    $where_part.= " OR f.idproject=$pid ";
		  }
		  $where_part.= ' ) ';
		  $sql = 'SELECT upload_time, file_name, one_time_upload_ID, idperson, username, p.idproject, p.name as project_name, f.status, f.changed '
		           .'FROM {file_upload_records} AS f LEFT JOIN {person} AS u ON uid=idperson LEFT JOIN {research_project} AS p ON p.idproject=f.idproject '
			   .'WHERE '.$where_part.' ORDER BY upload_time DESC LIMIT 0, 5';
		  $rows = array();
		  $res = db_query($sql);
		  while($r = db_fetch_object($res)){
		      $rows[] = array(
			    $r->upload_time,
			    l($r->project_name, 'node/'.$r->idproject),
			    $r->status,
		      );
		  }
		}
		
		if(empty($rows)){
		    $content.= '<p>(No uploading records.)</p>';
		}else{
		    $content.= theme_table($header, $rows);
		    $content.= '<p>'.l('','More recoreds').'</p>';
		}
    return $content;
}

/**
 * Menu callback for person chart
 */ 
function show_person_template() {
  		global $user;
		//drupal_set_html_head('<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js" type="text/javascript" /></script>');
		//drupal_add_js($module_path.'/calendar/jquery-1.3.1.js');
		$module_path = drupal_get_path('module', 'chart');
		drupal_add_js($module_path.'/calendar/ui/ui.core.js');
		drupal_add_js($module_path.'/calendar/ui/ui.datepicker.js');
		drupal_add_js($module_path.'/js/highcharts.js');
		drupal_add_js($module_path.'/js/modules/exporting.js');
		drupal_add_js($module_path.'/js/themes/grid.js');
		drupal_add_js($module_path.'/highslide/highslide.config.js');
		drupal_add_js($module_path.'/highslide/highslide-full.min.js');
		drupal_add_js($module_path.'/js/calendar.js');
		drupal_add_js($module_path.'/js/chart_person.js');

		drupal_add_css($module_path.'/calendar/demos/shadow.css');
		drupal_add_css($module_path.'/highslide/highslide.css');
		drupal_add_css($module_path.'/calendar/themes/base/ui.all.css');
		drupal_add_css($module_path.'/calendar/demos/demos.css');
		
		//add settings to js
		//Drupal.settings.chart.module_path
		drupal_add_js(array('chart'=>array('module_path'=>$module_path)),'setting');
		//Drupal.settings.chart.current_user
		drupal_add_js(array('chart'=>array('current_user'=>$user->uid)),'setting');
		//Drupal.settings.chart.handle_data
		drupal_add_js(array('chart'=>array('handle_data'=>url('chart/handle_data'))),'setting');
		//Drupal.settings.chart.getpersonprojects
		drupal_add_js(array('chart'=>array('getpersonprojects'=>url('person/projects/get/json'))),'setting');
		//Drupal.settings.chart.getpersondata
		drupal_add_js(array('chart'=>array('getpersondata'=>url('person/observations/get/json'))),'setting');
		
		$content = theme('show_person_chart');
		$content.= '<h3>Recent uploading</h3>';
		$header = array(
		      array('data'=>'Upload time'),
		      array('data'=>'Project'),
		      array('data'=>'Status'),
		);
		$sql = 'SELECT upload_time, file_name, one_time_upload_ID, idperson, username, p.idproject, p.name as project_name, f.status, f.changed FROM {file_upload_records} AS f LEFT JOIN {person} AS u ON uid=idperson LEFT JOIN {research_project} AS p ON p.idproject=f.idproject WHERE idperson=%d ORDER BY upload_time DESC LIMIT 0, 2';
		$rows = array();
		$res = db_query($sql, $user->uid);
		while($r = db_fetch_object($res)){
		      $rows[] = array(
			    $r->upload_time,
			    l($r->project_name, 'node/'.$r->idproject),
			    $r->status,
		      );
		}
		if(empty($rows)){
		    $content.= '<p>(No uploading records.)</p>';
		}else{
		    $content.= theme_table($header, $rows);
		    $content.= '<p>'.l('','More recoreds').'</p>';
		}
		
	return $content;
}

/**
 * Menu callback for chart/handle_data
 */
function json_chart_handle_data_callback(){
	drupal_set_header('Content-Type: text/plain; charset: utf-8');
	
	$start=$_GET['start'];$perid=$_GET['perid'];$proid=$_GET['proid'];$end=$_GET['end'];
	$time_array=array();
	$time_array=explode("-",$start);
	$time_string="[Date.UTC(".$time_array[0].','.$time_array[1].','.$time_array[2].'),null]]';
//[Date.UTC(2011, 10, 11, 8, 13),69]
	//$time_stamp=
	$base_url = "http://".$_SERVER['HTTP_HOST'].url('researcher/observations/data/json');
	//heart beat rate
	$url="$base_url?type=0&start=".$start."&end=".$end."&perid=".$perid."&proid=".$proid;
	$file = file_get_contents($url, true);
	//$file=str_ireplace('"','',$file);
	$first_part=substr($file,0,65);
	$second_part=substr($file,65);
	$first_part=str_ireplace('observations','observation1',$first_part);
	$second_part=str_ireplace('"','',$second_part);
	$result=$first_part.$second_part;
	$result=substr($result, 0, -1) ;

	//glucose
	$url="$base_url?type=2&start=".$start."&end=".$end."&perid=".$perid."&proid=".$proid;
	$file = file_get_contents($url, true);
	$glucose_first_part=substr($file,0,54);
	$glucose_first_part=substr( $glucose_first_part, 1 );//delete the first character '{'
	$glucose_first_part=str_ireplace('observations','observation2',$glucose_first_part);
	$glucose_second_part=substr($file,54);
	$glucose_second_part=str_ireplace('"','',$glucose_second_part);
	$glucose_result=$glucose_first_part.$glucose_second_part;
	$position=strpos($glucose_result,'null');
	if(position){
		//$glucose_string='"records":['.$time_string;
		
		//$glucose_result=str_ireplace('"records":null','"records":null]]',$glucose_result);
		//$glucose_result=str_ireplace('null','[[Date.UTC(2011, 10, 11, 10, 7),64]]',$glucose_result);
	}
	echo $result.','.$glucose_result;
}
/**
 * Implementation of hook_theme()
 */
function chart_person_theme() {
    return array(
	'show_person_chart' => array(
       'template' => 'person_chart_display',
       ),
    );
}