<?php
// $Id$

/**
* @file
* Module for fetching data from Goodreads.com.
* This module provides block content retrieved from a
* Goodreads.com bookshelf.
* @see http://www.goodreads.com
*/
/**
* Implementation of hook_menu()
*/
function chart_menu() {
  $items['chart'] = array(
    'title' => t('Observation'),
    'page callback' => 'show_template',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['person_chart'] = array(
    'title' => t('Observation'),
    'page callback' => 'show_person_template',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implementation of hook_theme()
 */
function chart_theme() {
    return array(
	'show_chart' => array(
       'template' => 'chart_display',
       ),
	  'show_person_chart'=>array(
		'template'=>'chart_person_display',
		),
    );
}
 
/**
 * Menu callback for researcher chart
 */ 
 
function show_template() {
		//drupal_set_html_head('<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js" type="text/javascript" /></script>');
		//drupal_add_js($module_path.'/calendar/jquery-1.3.1.js');
		$module_path = drupal_get_path('module', 'chart');
		drupal_add_js($module_path.'/calendar/ui/ui.core.js');
		drupal_add_js($module_path.'/calendar/ui/ui.datepicker.js');
		drupal_add_js($module_path.'/js/highcharts.js');
		drupal_add_js($module_path.'/js/modules/exporting.js');
		drupal_add_js($module_path.'/js/themes/grid.js');
		drupal_add_js($module_path.'/highslide/highslide.config.js');
		drupal_add_js($module_path.'/highslide/highslide-full.min.js');
		drupal_add_css($module_path.'/js/calendar.js');

		drupal_add_css($module_path.'/calendar/demos/shadow.css');
		drupal_add_css($module_path.'/highslide/highslide.css');
		drupal_add_css($module_path.'/calendar/themes/base/ui.all.css');
		drupal_add_css($module_path.'/calendar/demos/demos.css');
    return theme('show_chart');
}

/**
 * Menu callback for person chart
 */ 
function show_person_template() {
		//drupal_set_html_head('<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js" type="text/javascript" /></script>');
		//drupal_add_js($module_path.'/calendar/jquery-1.3.1.js');
		$module_path = drupal_get_path('module', 'chart');
		drupal_add_js($module_path.'/calendar/ui/ui.core.js');
		drupal_add_js($module_path.'/calendar/ui/ui.datepicker.js');
		drupal_add_js($module_path.'/js/highcharts.js');
		drupal_add_js($module_path.'/js/modules/exporting.js');
		drupal_add_js($module_path.'/js/themes/grid.js');
		drupal_add_js($module_path.'/highslide/highslide.config.js');
		drupal_add_js($module_path.'/highslide/highslide-full.min.js');
		drupal_add_css($module_path.'/js/calendar.js');

		drupal_add_css($module_path.'/calendar/demos/shadow.css');
		drupal_add_css($module_path.'/highslide/highslide.css');
		drupal_add_css($module_path.'/calendar/themes/base/ui.all.css');
		drupal_add_css($module_path.'/calendar/demos/demos.css');


    return theme('show_person_chart');
}
/**
 * Implementation of hook_theme()
 */
function chart_person_theme() {
    return array(
	'show_person_chart' => array(
       'template' => 'person_chart_display',
       ),
    );
}