<?php

/**
 * Implementation of hook_help()
 */
function reProjectBlock_help($path, $arg){
    switch ($path) {
        
        // In main module help page
        case 'admin/help#reProjectBlock':
            return '<p>'.t("This module help to generate blocks for each Research Project.").'</p>';
    }
}

/**
 * Implemenation of hook_block()
 */
function reProjectBlock_block($op = 'list', $delta = 0, $edit = array()){
    if($op == 'list'){
        $blocks = array();
        
        //TODO:get projects list
        $get_list_sql = "SELECT id, name, path FROM {research_projects}";
        $res = db_query($get_list_sql);
        while($project = db_fetch_object($res)){
            $blocks[$project->id] = array(
                'info'   => $project->name,
                'cache'  => BLOCK_CACHE_GLOBAL,
                'weight' => 1,
                'status' => 0,
            );
        }
        
        return $blocks;
    }elseif($op == 'configure'){
        
    }elseif($op == 'save'){
        
    }elseif($op == 'view'){
        drupal_add_css(drupal_get_path('module','reProjectBlock').'/project_blocks.css');
        
        //get block info
        $project = load_project($delta,'id');
        
        $block = array(
            'subject' => t($project->name), 
            'content' => display_project_introduction_block($project),
        );
        return $block;
    }
}

/**
 * Implementation of hook_theme()
 */
function reProjectBlock_theme(){
    return array(
        'project_introduction_block' => array(
            'template' => 'project_introduction_block',
	    'arguments' => array(
                'block' => NULL,
            ),
        ),
    );
}

/**
 *
 */
function display_project_introduction_block($project){
    //get project info
    $block = array(
        'content' => node_teaser($project->introduction),
        'read_more' => url("project/{$project->path}"),  
    );
    
    return theme('project_introduction_block',$block);
}